export const {
  user = '',
  password = '',
  host = '',
  port = '',
  dbname = '',
  JWT_SECRET = '',
  WHATSAPP_TOKEN = '',
  WHATSAPP_PHONE_NUMBER_ID = '',
  API_GATEWAY_URL = '',
  FRONTEND_URL = 'http://localhost:3000'
} = Bun.env
